version: "3.7"

services:
  adguardhome:
    image: adguard/adguardhome:latest
    ports:
      - 53:53
      - 853:853
      - 784:784
    networks:
      - traefik-public
      - for-unbound
    volumes:
      - ./conf:/opt/adguardhome/conf
      - ./work:/opt/adguardhome/work
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
        monitor: 10s
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first
        monitor: 10s
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public

        - traefik.http.routers.adguardhome-http.rule=Host(`dns.hen.ee`) # Change this
        - traefik.http.routers.adguardhome-http.entrypoints=http
        - traefik.http.routers.adguardhome-http.middlewares=https-redirect

        - traefik.http.routers.adguardhome-https.rule=Host(`dns.hen.ee`) # Change this
        - traefik.http.routers.adguardhome-https.entrypoints=https
        - traefik.http.routers.adguardhome-https.tls=true
        - traefik.http.routers.adguardhome-https.tls.certresolver=le

        - traefik.http.services.adguardhome.loadbalancer.server.port=3000
        # 53/udp
        #- traefik.udp.routers.adguardhome-dns.entrypoints=dns
        #- traefik.udp.routers.adguardhome-dns.service=adguardhome-dns
        #- traefik.udp.services.adguardhome-dns.loadbalancer.server.port=53
        # 53/tcp
        #- traefik.tcp.routers.adguardhome-dns.rule=HostSNI(`*`)
        #- traefik.tcp.routers.adguardhome-dns.entrypoints=dns
        #- traefik.tcp.routers.adguardhome-dns.service=adguardhome-dns-tcp
        #- traefik.tcp.services.adguardhome-dns.loadbalancer.server.port=53

  unbound:
    image: mvance/unbound:latest
    networks:
      - for-unbound
    configs:
      - source: unbound-conf
        target: /opt/unbound/etc/unbound/unbound.conf
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
        monitor: 10s
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first
        monitor: 10s


networks:
  traefik-public:
    external: true
  for-unbound:

configs:
  unbound-conf:
    file: ./unbound.conf